Try to fix github actions permissions

diff --git a/.github/workflows/pullRequest.yml b/.github/workflows/pullRequest.yml
--- a/.github/workflows/pullRequest.yml
+++ b/.github/workflows/pullRequest.yml
@@ -29,6 +29,11 @@ jobs:
       options: --user 0
       #options: --user $(id -u):$(id -g)
     steps: 
+    - name: Debug permissions
+      run: |
+        id
+        ls -ld /__w /__w/_temp /__w/_temp/_runner_file_commands || true
+        touch /__w/_temp/testfile || echo "Cannot write"
     - name: Fix permissions
       run: sudo chown -R 1000:1000 /__w || true
     - name: checkout code
